WebOdev/Models/Kullanici.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Web12412412.Models
{
    [Table("KullaniciTbl")]
    public class Kullanici

    {
        [Key]
        public int UserId { get; set; }

        [Required(ErrorMessage = "Lütfen adınızı giriniz.")]
        [Display(Name = "Adınız")]
        public string FirstName { get; set; } = string.Empty;

        [Required(ErrorMessage = "Lütfen soyadınızı giriniz.")]
        [Display(Name = "Soyadınız")]
        public string LastName { get; set; } = string.Empty;

        [Display(Name = "E-mail adresiniz")]
        [Required(ErrorMessage = "Lütfen e-mail adresinizi giriniz.")]
        [DataType(DataType.EmailAddress)] // E-mail adresi formatında olmalı
        public string Email { get; set; } = string.Empty;

        [Required(ErrorMessage = "Lütfen şifrenizi giriniz.")]
        [Display(Name = "Şifre")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "Şifre Onay")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Şifreleriniz uyuşmuyor.")]
        public string CPassword { get; set; }

        [Required(ErrorMessage = "Lütfen telefon numaranızı giriniz.")]
        [Display(Name = "Telefon Numaranız")]
        [DataType(DataType.PhoneNumber)]
        public string PhoneNumber { get; set; } = string.Empty;

        [Required(ErrorMessage = "Lütfen Yaşınızı Giriniz")]
        [Display(Name = "Yaşınız")]
        public int Age { get; set; }

        [Required(ErrorMessage = "Lütfen Kimlik Numaranızı"), RegularExpression(@"^([0-9]{11})$", ErrorMessage = "Geçersiz Kimlik No")] // Kimlik numarası formatında olmalı
        [Display(Name = "Kimlik Numaranız")]
        [StringLength(11, ErrorMessage = "Kimlik Numaranız 11 haneli olmalıdır.")]
        public string IdentityNumber { get; set; } = string.Empty;
    }
}

WebOdev/Controllers/BiletController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Web12412412.Models;

namespace WebOdev.Controllers
{
    public class BiletController : Controller
    {
        BiletContext _context = new BiletContext();

        // GET: Bilet
        public async Task<IActionResult> Index()
        {
            var biletContext = _context.Biletler.Include(b => b.Ucak);
            return View(await biletContext.ToListAsync());
        }

        // GET: Bilet/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Biletler == null)
            {
                return NotFound();
            }

            var bilet = await _context.Biletler
                .Include(b => b.Ucak)
                .FirstOrDefaultAsync(m => m.BiletId == id);
            if (bilet == null)
            {
                return NotFound();
            }

            return View(bilet);
        }

        // GET: Bilet/Create
        public IActionResult Create()
        {
            ViewData["UcakId"] = new SelectList(_context.Ucaklar, "UcakId", "UcakAdi");
            return View();
        }

        // POST: Bilet/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BiletId,KalkisYeri,VarisYeri,GidisTarihi,DonusTarihi,KalkisSaat,UcakId,KoltukNumarasi")] Bilet bilet)
        {
            List<Sehir> sehirListesi = _context.Sehir.ToList();

            ViewBag.SehirListesi = new SelectList(sehirListesi, "Id", "SehirAdi");


            if (ModelState.IsValid)
            {
                _context.Add(bilet);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UcakId"] = new SelectList(_context.Ucaklar, "UcakId", "UcakAdi", bilet.UcakId);
            return View(bilet);
        }

        // GET: Bilet/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Biletler == null)
            {
                return NotFound();
            }

            var bilet = await _context.Biletler.FindAsync(id);
            if (bilet == null)
            {
                return NotFound();
            }
            ViewData["UcakId"] = new SelectList(_context.Ucaklar, "UcakId", "UcakAdi", bilet.UcakId);
            return View(bilet);
        }

        // POST: Bilet/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BiletId,KalkisYeri,VarisYeri,GidisTarihi,DonusTarihi,KalkisSaat,UcakId,KoltukNumarasi")] Bilet bilet)
        {
            if (id != bilet.BiletId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bilet);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BiletExists(bilet.BiletId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UcakId"] = new SelectList(_context.Ucaklar, "UcakId", "UcakAdi", bilet.UcakId);
            return View(bilet);
        }

        // GET: Bilet/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Biletler == null)
            {
                return NotFound();
            }

            var bilet = await _context.Biletler
                .Include(b => b.Ucak)
                .FirstOrDefaultAsync(m => m.BiletId == id);
            if (bilet == null)
            {
                return NotFound();
            }

            return View(bilet);
        }

        // POST: Bilet/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Biletler == null)
            {
                return Problem("Entity set 'BiletContext.Biletler'  is null.");
            }
            var bilet = await _context.Biletler.FindAsync(id);
            if (bilet != null)
            {
                _context.Biletler.Remove(bilet);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BiletExists(int id)
        {
          return (_context.Biletler?.Any(e => e.BiletId == id)).GetValueOrDefault();
        }

    }
}

WebOdev/Controllers/KullaniciController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Web12412412.Models;

namespace Web12412412.Controllers
{
    public class KullaniciController : Controller
    {
        BiletContext _context = new BiletContext();

        public IActionResult Login()
        {
            if (HttpContext.Session.GetString("SessionKullanici") != null)
            {
                var cookoption = new CookieOptions();
                {
                    cookoption.Expires = DateTime.Now.AddDays(1);
                }
                Response.Cookies.Append("Kullanici", HttpContext.Session.GetString("SessionKullanici"), cookoption);
                return RedirectToAction("Index", "Kullanici");
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(Kullanici kullanici)
        {

            var login = _context.Kullanicilar.Where(_context => _context.Email == kullanici.Email && _context.Password == kullanici.Password).FirstOrDefault();
            if (login != null)
            {
                HttpContext.Session.SetString("SessionKullanici",kullanici.FirstName );
                var cookoption = new CookieOptions();
                {
                    cookoption.Expires = DateTime.Now.AddDays(1);
                }
                Response.Cookies.Append("Kullanici", HttpContext.Session.GetString("SessionKullanici"), cookoption);
                return RedirectToAction("Index", "Kullanici");
            }
            else
            {
                ViewBag.Message = "Kullanıcı adı veya şifre hatalı";
                return View();
            }
        }


        // GET: Kullanici
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("SessionAdmin") != null)
            {
                return _context.Kullanicilar != null ?
                          View(await _context.Kullanicilar.ToListAsync()) :
                          Problem("Entity set 'BiletContext.Kullanicilar'  is null.");
            }
            else
            {
                TempData["Mesaj4"] = "Lütfen Login olunuz";
                return RedirectToAction("Login", "Admin");
            }

        }

        // GET: Kullanici/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Kullanicilar == null)
            {
                return NotFound();
            }

            var kullanici = await _context.Kullanicilar
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (kullanici == null)
            {
                return NotFound();
            }

            return View(kullanici);
        }

        // GET: Kullanici/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Kullanici/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,FirstName,LastName,Email,Password,CPassword,PhoneNumber,Age,IdentityNumber")] Kullanici kullanici)
        {
            if (ModelState.IsValid)
            {
                _context.Add(kullanici);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(kullanici);
        }

        // GET: Kullanici/Create
        public IActionResult Create2()
        {
            return View();
        }

        // POST: Kullanici/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create2([Bind("UserId,FirstName,LastName,Email,Password,CPassword,PhoneNumber,Age,IdentityNumber")] Kullanici kullanici)
        {
            if (ModelState.IsValid)
            {
                _context.Add(kullanici);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(kullanici);
        }

        public IActionResult Profil(Kullanici kullanici)
        {
            if (HttpContext.Session.GetString("SessionUser") != null)
            {
                return View(kullanici);
            }
            else
            {
                TempData["Mesaj4"] = "Lütfen Login olunuz";
                return RedirectToAction("Login", "Home");
            }
            /*
            if (ModelState.IsValid)
            {
                return View(kullanici);
            }
            else
            {
                ViewBag.Mesaj = "Lütfen bilgilerinizi kontrol ediniz.";
                return View("Index");
            }
            var login = BiletContext.Adminler.Where(x => x.AdminName == admin.AdminName && x.Password == admin.Password).FirstOrDefault();
            if (login != null)
            {
                HttpContext.Session.SetString("SessionAdmin", admin.AdminName);
                var cookoption = new CookieOptions();
                {
                    cookoption.Expires = DateTime.Now.AddDays(1);
                }
                Response.Cookies.Append("Admin", HttpContext.Session.GetString("SessionAdmin"), cookoption);
                return RedirectToAction("Index", "Admin");
            }
            else
            {
                ViewBag.Message = "Kullanıcı adı veya şifre hatalı";
                return View();
            }
            */
        }

        // GET: Kullanici/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Kullanicilar == null)
            {
                return NotFound();
            }

            var kullanici = await _context.Kullanicilar.FindAsync(id);
            if (kullanici == null)
            {
                return NotFound();
            }
            return View(kullanici);
        }

        // POST: Kullanici/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,FirstName,LastName,Email,Password,CPassword,PhoneNumber,Age,IdentityNumber")] Kullanici kullanici)
        {
            if (id != kullanici.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(kullanici);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KullaniciExists(kullanici.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(kullanici);
        }

        // GET: Kullanici/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Kullanicilar == null)
            {
                return NotFound();
            }

            var kullanici = await _context.Kullanicilar
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (kullanici == null)
            {
                return NotFound();
            }

            return View(kullanici);
        }

        // POST: Kullanici/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Kullanicilar == null)
            {
                return Problem("Entity set 'BiletContext.Kullanicilar'  is null.");
            }
            var kullanici = await _context.Kullanicilar.FindAsync(id);
            if (kullanici != null)
            {
                _context.Kullanicilar.Remove(kullanici);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KullaniciExists(int id)
        {
            return (_context.Kullanicilar?.Any(e => e.UserId == id)).GetValueOrDefault();
        }

        public IActionResult Cikis()
        { 
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }

    }
}

WebOdev/Views/Kullanici/Create.cshtml
@model Web12412412.Models.Kullanici

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h1>Create</h1>

<h4>Kullanici</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CPassword" class="control-label"></label>
                <input asp-for="CPassword" class="form-control" />
                <span asp-validation-for="CPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdentityNumber" class="control-label"></label>
                <input asp-for="IdentityNumber" class="form-control" />
                <span asp-validation-for="IdentityNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebOdev/Views/Kullanici/Create2.cshtml
@model Web12412412.Models.Kullanici

@{
    ViewData["Title"] = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Üye Ol</h1>

<h4>Kullanici</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login" asp-controller="Kullanici">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CPassword" class="control-label"></label>
                <input asp-for="CPassword" class="form-control" />
                <span asp-validation-for="CPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdentityNumber" class="control-label"></label>
                <input asp-for="IdentityNumber" class="form-control" />
                <span asp-validation-for="IdentityNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Üye Ol" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

WebOdev/Views/Kullanici/Delete.cshtml
@model Web12412412.Models.Kullanici

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Kullanici</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CPassword)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CPassword)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdentityNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdentityNumber)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="UserId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebOdev/Views/Kullanici/Details.cshtml
@model Web12412412.Models.Kullanici

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h1>Profil</h1>

<div>
    <h4>Kullanici</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CPassword)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CPassword)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdentityNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdentityNumber)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.UserId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebOdev/Views/Kullanici/Edit.cshtml
@model Web12412412.Models.Kullanici

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h1>Edit</h1>

<h4>Kullanici</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="UserId" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CPassword" class="control-label"></label>
                <input asp-for="CPassword" class="form-control" />
                <span asp-validation-for="CPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdentityNumber" class="control-label"></label>
                <input asp-for="IdentityNumber" class="form-control" />
                <span asp-validation-for="IdentityNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebOdev/Views/Kullanici/Login.cshtml
@model Web12412412.Models.Kullanici

@{
    ViewData["Title"] = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Kullanici Giriş</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Bilet">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Giriş Yap" class="btn btn-primary" />
            </div>
            <br />
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Home">Ana Sayfa</a>
</div>