WebOdev/Controllers/SehirController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Web12412412.Models;

namespace WebOdev.Controllers
{
    public class SehirController : Controller
    {
        BiletContext _context = new BiletContext();

        // GET: Sehir
        public async Task<IActionResult> Index()
        {
              return _context.Sehir != null ? 
                          View(await _context.Sehir.ToListAsync()) :
                          Problem("Entity set 'BiletContext.Sehir'  is null.");
        }

        // GET: Sehir/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Sehir == null)
            {
                return NotFound();
            }

            var sehir = await _context.Sehir
                .FirstOrDefaultAsync(m => m.SehirId == id);
            if (sehir == null)
            {
                return NotFound();
            }

            return View(sehir);
        }

        // GET: Sehir/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Sehir/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SehirId,SehirAdi")] Sehir sehir)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sehir);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sehir);
        }

        // GET: Sehir/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Sehir == null)
            {
                return NotFound();
            }

            var sehir = await _context.Sehir.FindAsync(id);
            if (sehir == null)
            {
                return NotFound();
            }
            return View(sehir);
        }

        // POST: Sehir/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SehirId,SehirAdi")] Sehir sehir)
        {
            if (id != sehir.SehirId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sehir);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SehirExists(sehir.SehirId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sehir);
        }

        // GET: Sehir/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Sehir == null)
            {
                return NotFound();
            }

            var sehir = await _context.Sehir
                .FirstOrDefaultAsync(m => m.SehirId == id);
            if (sehir == null)
            {
                return NotFound();
            }

            return View(sehir);
        }

        // POST: Sehir/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Sehir == null)
            {
                return Problem("Entity set 'BiletContext.Sehir'  is null.");
            }
            var sehir = await _context.Sehir.FindAsync(id);
            if (sehir != null)
            {
                _context.Sehir.Remove(sehir);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SehirExists(int id)
        {
          return (_context.Sehir?.Any(e => e.SehirId == id)).GetValueOrDefault();
        }
    }
}

WebOdev/Controllers/UcakController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Web12412412.Models;

namespace Web12412412.Controllers
{
    public class UcakController : Controller
    {
        BiletContext _context = new BiletContext();

        // GET: Ucak
        public async Task<IActionResult> Index()
        {
            if(HttpContext.Session.GetString("SessionAdmin") != null)
            {
                return _context.Ucaklar != null ?
                       View(await _context.Ucaklar.ToListAsync()) :
                       Problem("Entity set 'BiletContext.Ucaklar'  is null.");
            }
            else
            {
                TempData["Mesaj2"] = "Lütfen Login olunuz";
                return RedirectToAction("Login", "Admin");
            }
           
        }

        // GET: Ucak/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Ucaklar == null)
            {
                return NotFound();
            }

            var ucak = await _context.Ucaklar
                .FirstOrDefaultAsync(m => m.UcakId == id);
            if (ucak == null)
            {
                return NotFound();
            }

            return View(ucak);
        }

        // GET: Ucak/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Ucak/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UcakId,UcakAdi,KoltukSayisi,Fiyat,doluKoltukSayisi")] Ucak ucak)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ucak);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ucak);
        }

        // GET: Ucak/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Ucaklar == null)
            {
                return NotFound();
            }

            var ucak = await _context.Ucaklar.FindAsync(id);
            if (ucak == null)
            {
                return NotFound();
            }
            return View(ucak);
        }

        // POST: Ucak/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UcakId,UcakAdi,KoltukSayisi,Fiyat,doluKoltukSayisi")] Ucak ucak)
        {
            if (id != ucak.UcakId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ucak);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UcakExists(ucak.UcakId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ucak);
        }

        // GET: Ucak/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Ucaklar == null)
            {
                return NotFound();
            }

            var ucak = await _context.Ucaklar
                .FirstOrDefaultAsync(m => m.UcakId == id);
            if (ucak == null)
            {
                return NotFound();
            }

            return View(ucak);
        }

        // POST: Ucak/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Ucaklar == null)
            {
                return Problem("Entity set 'BiletContext.Ucaklar'  is null.");
            }
            var ucak = await _context.Ucaklar.FindAsync(id);
            if (ucak != null)
            {
                _context.Ucaklar.Remove(ucak);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UcakExists(int id)
        {
          return (_context.Ucaklar?.Any(e => e.UcakId == id)).GetValueOrDefault();
        }
    }
}

WebOdev/Controllers/UcusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Web12412412.Models;

namespace WebOdev.Controllers
{
    public class UcusController : Controller
    {
        BiletContext _context = new BiletContext();

        // GET: Ucus
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("SessionAdmin") != null)
            {
                var biletContext = _context.Ucuslar.Include(u => u.Ucak);
                return View(await biletContext.ToListAsync());
            }
            else
            {
                TempData["Mesaj3"] = "Lütfen Login olunuz";
                return RedirectToAction("Login", "Admin");
            }
        }

        // GET: Ucus/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Ucuslar == null)
            {
                return NotFound();
            }

            var ucus = await _context.Ucuslar
                .Include(u => u.Ucak)
                .FirstOrDefaultAsync(m => m.UcusId == id);
            if (ucus == null)
            {
                return NotFound();
            }

            return View(ucus);
        }

        // GET: Ucus/Create
        public IActionResult Create()
        {
            ViewData["UcakId"] = new SelectList(_context.Ucaklar, "UcakId", "UcakAdi");
            return View();
        }

        // POST: Ucus/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UcusId,Nereden,Nereye,GidisTarihi,DonusTarihi,KalkisSaat,VarisSaat,UcakId,doluKoltukSayisi")] Ucus ucus)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ucus);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UcakId"] = new SelectList(_context.Ucaklar, "UcakId", "UcakAdi", ucus.UcakId);
            return View(ucus);
        }

        // GET: Ucus/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Ucuslar == null)
            {
                return NotFound();
            }

            var ucus = await _context.Ucuslar.FindAsync(id);
            if (ucus == null)
            {
                return NotFound();
            }
            ViewData["UcakId"] = new SelectList(_context.Ucaklar, "UcakId", "UcakAdi", ucus.UcakId);
            return View(ucus);
        }

        // POST: Ucus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UcusId,Nereden,Nereye,GidisTarihi,DonusTarihi,KalkisSaat,VarisSaat,UcakId,doluKoltukSayisi")] Ucus ucus)
        {
            if (id != ucus.UcusId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ucus);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UcusExists(ucus.UcusId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UcakId"] = new SelectList(_context.Ucaklar, "UcakId", "UcakAdi", ucus.UcakId);
            return View(ucus);
        }

        // GET: Ucus/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Ucuslar == null)
            {
                return NotFound();
            }

            var ucus = await _context.Ucuslar
                .Include(u => u.Ucak)
                .FirstOrDefaultAsync(m => m.UcusId == id);
            if (ucus == null)
            {
                return NotFound();
            }

            return View(ucus);
        }

        // POST: Ucus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Ucuslar == null)
            {
                return Problem("Entity set 'BiletContext.Ucuslar'  is null.");
            }
            var ucus = await _context.Ucuslar.FindAsync(id);
            if (ucus != null)
            {
                _context.Ucuslar.Remove(ucus);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UcusExists(int id)
        {
          return (_context.Ucuslar?.Any(e => e.UcusId == id)).GetValueOrDefault();
        }
    }
}

WebOdev/Views/Shared/_AboutPageLayout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <title>GDC Airways - About</title>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="GDC-AboutCSS.css">
        <link href="https://fonts.googleapis.com/css?family=Kaushan+Script|Paytone+One" rel="stylesheet">

        <link href="~/css/aboutpage.css" rel="stylesheet" />
    
    </head>


    body>

        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                <a href="" class="navbar-brand"><i class="fa fa-plane"></i> SAU Airways</a>
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a href="@Url.Action("Index", "Home")"><strong>@_localization.GetKey("home").Value</strong></a></li>
                        <li><a href="@Url.Action("Index", "About")"><strong>@_localization.GetKey("about").Value</strong></a></li>
                        @if (Context.Session.GetString("UserId") is not null)
                        {
                            <li><a href="@Url.Action("Index", "MyTickets")"><strong>@_localization.GetKey("myTickets").Value</strong></a></li>
                        }
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                @_localization.GetKey("language").Value <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="@Url.Action("ChangeLanguage", "Home", new { culture = "en-US" })" class="dropdown-item">
                                        <i class="flag-icon flag-icon-gb"></i> English
                                    </a>
                                </li>
                                <li>
                                    <a href="@Url.Action("ChangeLanguage", "Home", new { culture = "tr-TR" })" class="dropdown-item">
                                        <i class="flag-icon flag-icon-tr"></i> Türkçe
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        @if (Context.Session.GetString("UserId") is null)
                        {
                            <li><a href="@Url.Action("Create", "Register")"><strong>@_localization.GetKey("signup").Value </strong><i class="fas fa-user-plus"></i></a></li>
                            <li><a href="@Url.Action("Login", "Login")"><strong>@_localization.GetKey("signin").Value </strong><i class="fas fa-user"></i></a></li>
                        }
                        else
                        {
                            <li style="color :white ; margin-top: 20px"><strong>@Context.Session.GetString("UserName")</strong></li>
                            <li></li>
                            <li></li>
                            <li><a href="@Url.Action("PLogout", "Login")"><strong>@_localization.GetKey("logout").Value</strong></a></li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
        <div>
            @RenderBody();
        </div>

        <h1>@_localization.GetKey("about").Value</h1>
        <div class="container" id="cell">
            <p>
                @_localization.GetKey("aboutDescription").Value
            </p>
            <br>
            <p>
                <h3>@_localization.GetKey("aboutTitle1").Value</h3>
                 @_localization.GetKey("aboutTitleDes1").Value
            </p>
            <p>
                <h3>@_localization.GetKey("aboutTitle2").Value</h3>
                    @_localization.GetKey("aboutTitleDes2").Value
            </p>
            <p>
                <h3>@_localization.GetKey("aboutTitle3").Value</h3>
                    @_localization.GetKey("aboutTitleDes3").Value
            </p>
            <p>
                <h3>@_localization.GetKey("aboutTitle4").Value</h3>
                    @_localization.GetKey("aboutTitleDes4").Value
            </p>
        </div>

    /body>

</html>

WebOdev/Views/Shared/_AdminPageLayout.cshtml
<!DOCTYPE html>
<!-- Created By CodingNepal -->
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <title>Sidebar Menu with sub-menu | CodingNepal</title>
    <link rel="stylesheet" href="style.css">
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link href="~/css/admin.css" rel="stylesheet" />

</head>
<body>
    <div class="btn">
        <span class="fas fa-bars"></span>
    </div>
    <nav class="sidebar">
        <div class="text">
            <i class="fa fa-plane"></i>
            SAU Airways
        </div>
        <ul>
            <li class="active"><a href="#"> <i class="fas fa-qrcode"></i> Dashboard</a></li>
            <li>
                <a href="#" class="feat-btn">
                    <i class="fa fa-laptop"></i>
                    Planes
                    <span class="fas fa-caret-down first"></span>
                </a>
                <ul class="feat-show">
                    <li><a href="@Url.Action("Create", "PlaneInfo")">Add Plane</a></li>
                    <li><a href="@Url.Action("Index", "PlaneInfo")">View Details</a></li>
                </ul>
            </li>
            <li>
                <a href="#" class="serv-btn">
                    <i class="fa fa-laptop"></i>
                    Flight
                    <span class="fas fa-caret-down second"></span>
                </a>
                <ul class="serv-show">
                    <li><a href="@Url.Action("Create", "Flights")">Add Flight</a></li>
                    <li><a href="@Url.Action("Index", "Flights")">Flight Details</a></li>
                </ul>
            </li>
            <li><a href="@Url.Action("ALogout", "Login")"><i class="fa fa-power-off" aria-hidden="true"></i> Log Out</a></li>
        </ul>
    </nav>
   
    <main role="main" class="pb-3" >
        @RenderBody()
    </main>
    <div class="content" >
        <div class="header">
            Welcome to Admin Panel 
        </div>
        <div class="header">
            @Context.Session.GetString("AdminName") 
        </div>
        <div class="header">
             @Context.Session.GetString("AdminMail")
        </div>
    </div>
    <script>
        $('.btn').click(function () {
            $(this).toggleClass("click");
            $('.sidebar').toggleClass("show");
        });
        $('.feat-btn').click(function () {
            $('nav ul .feat-show').toggleClass("show");
            $('nav ul .first').toggleClass("rotate");
        });
        $('.serv-btn').click(function () {
            $('nav ul .serv-show').toggleClass("show1");
            $('nav ul .second').toggleClass("rotate");
        });
        $('nav ul li').click(function () {
            $(this).addClass("active").siblings().removeClass("active");
        });
    </script>
</body>
</html>

WebOdev/Views/Shared/_HomePageLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <title>SAU Airways</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Pacifico|Paytone+One" rel="stylesheet">
    <!-- Add your custom CSS files -->
    <link href="~/css/homepage.css" rel="stylesheet" />
    <link href="~/css/home3.css" rel="stylesheet" />
    <link href="~/css/home2.css" rel="stylesheet" />
</head>

<body>
    <!-- NavBar -->
    <nav class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <a href="#" class="navbar-brand"><i class="fa fa-plane"></i> SAU Airways</a>
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li ><a href="@Url.Action("Index", "Home")"><strong>@_localization.GetKey("home").Value</strong></a></li>
                    <li><a href="@Url.Action("Index", "About")"><strong>@_localization.GetKey("about").Value</strong></a></li>
                    @if (Context.Session.GetString("UserId") is not null)
                    {
                        <li><a href="@Url.Action("Index", "MyTickets")"><strong>@_localization.GetKey("myTickets").Value</strong></a></li>
                    }
                    
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            @_localization.GetKey("language").Value <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="@Url.Action("ChangeLanguage", "Home", new { culture = "en-US" })" class="dropdown-item">
                                    <i class="flag-icon flag-icon-gb"></i> English
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("ChangeLanguage", "Home", new { culture = "tr-TR" })" class="dropdown-item">
                                    <i class="flag-icon flag-icon-tr"></i> Türkçe
                                </a>
                            </li>
                        </ul>
                    </li>

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (Context.Session.GetString("UserId") is null)
                    {
                        <li><a href="@Url.Action("Create", "Register")"><strong>@_localization.GetKey("signup").Value </strong><i class="fas fa-user-plus"></i></a></li>
                        <li><a href="@Url.Action("Login", "Login")"><strong>@_localization.GetKey("signin").Value </strong><i class="fas fa-user"></i></a></li>
                    }
                    else
                    {
                        <li style="color :white ; margin-top: 20px"><strong>@Context.Session.GetString("UserName")</strong></li>
                        <li></li>
                        <li></li>
                        <li ><a href="@Url.Action("PLogout", "Login")"><strong>@_localization.GetKey("logout").Value</strong></a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <!-- NavBar End -->

    <div>
        @RenderBody()
    </div>
</body>

</html>

WebOdev/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebProje</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Work+Sans&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Admin" asp-action="Login">Admin Panel</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Ucak" asp-action="Index">Ucaklar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Sehir" asp-action="Index">Güzergah</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Ucus" asp-action="Index">Uçuşlar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Kullanici" asp-action="Index">Kullanıcılar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Admin" asp-action="Cikis">Çıkış</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebProje - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>